# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        # Фиксация размера экрана
        # MainWindow.resize(800, 700)  # - Исходное
        MainWindow.setFixedSize(800, 700)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(51, 51, 51);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "font: 14pt \"Arial\";\n"
                                 )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("alignment: center;\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setIconSize(QtCore.QSize(20, 25))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_viewed = QtWidgets.QWidget()
        self.tab_viewed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tab_viewed.setStyleSheet("")
        self.tab_viewed.setObjectName("tab_viewed")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_viewed)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.viewed_text_layout = QtWidgets.QHBoxLayout()
        self.viewed_text_layout.setObjectName("viewed_text_layout")
        self.text_viewed = QtWidgets.QLabel(self.tab_viewed)
        self.text_viewed.setStyleSheet("font: 75 italic 18pt \"Helvetica\";\n"
"color: rgb(255, 204, 0);\n"
"border-bottom: 2px solid gray;\n"
"padding-bottom: 10px;")
        self.text_viewed.setObjectName("text_viewed")
        self.viewed_text_layout.addWidget(self.text_viewed)
        self.verticalLayout_2.addLayout(self.viewed_text_layout)
        self.viewed_scrollArea = QtWidgets.QScrollArea(self.tab_viewed)
        self.viewed_scrollArea.setWidgetResizable(True)
        self.viewed_scrollArea.setObjectName("viewed_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 762, 553))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")

        # Убирает рамку у QScrollArea
        self.viewed_scrollArea.setFrameStyle(QtWidgets.QFrame.NoFrame)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.viewed_movie_widgets_layout = QtWidgets.QVBoxLayout()
        self.viewed_movie_widgets_layout.setObjectName("viewed_movie_widgets_layout")
        self.label_in_process = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_in_process.setStyleSheet("font: 87 30pt \"Arial Black\";\n"
"color: rgb(150, 150, 150);")
        self.label_in_process.setObjectName("label_in_process")
        self.viewed_movie_widgets_layout.addWidget(self.label_in_process)
        self.horizontalLayout_3.addLayout(self.viewed_movie_widgets_layout)
        self.viewed_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.viewed_scrollArea)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/favorites.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_viewed, icon, "")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setAutoFillBackground(False)
        self.tab_search.setObjectName("tab_search")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_search)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_line_layout = QtWidgets.QHBoxLayout()
        self.search_line_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.search_line_layout.setSpacing(0)
        self.search_line_layout.setObjectName("search_line_layout")
        self.label_search = QtWidgets.QLineEdit(self.tab_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_search.sizePolicy().hasHeightForWidth())
        self.label_search.setSizePolicy(sizePolicy)
        self.label_search.setMinimumSize(QtCore.QSize(0, 40))
        self.label_search.setStyleSheet("border-color: rgb(255, 26, 29);")
        self.label_search.setFrame(True)
        self.label_search.setPlaceholderText("Введите название фильма...")
        self.label_search.setObjectName("label_search")
        self.search_line_layout.addWidget(self.label_search)
        self.btn_delete = QtWidgets.QPushButton(self.tab_search)
        self.btn_delete.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_delete.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.btn_delete.setText("")
        self.btn_delete.setCheckable(False)
        self.btn_delete.setAutoRepeat(False)
        self.btn_delete.setAutoExclusive(False)
        self.btn_delete.setAutoDefault(False)
        self.btn_delete.setDefault(False)
        self.btn_delete.setFlat(False)
        self.btn_delete.setObjectName("btn_delete")

        # Добавление иконки для кнопки очистки
        icon_delete = QtGui.QIcon()
        icon_delete.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon_delete)

        self.search_line_layout.addWidget(self.btn_delete)
        self.btn_search = QtWidgets.QPushButton(self.tab_search)
        self.btn_search.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_search.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.btn_search.setCheckable(False)
        self.btn_search.setAutoRepeat(False)
        self.btn_search.setAutoExclusive(False)
        self.btn_search.setAutoDefault(False)
        self.btn_search.setDefault(False)
        self.btn_search.setFlat(False)
        self.btn_search.setObjectName("btn_search")
        self.search_line_layout.addWidget(self.btn_search)
        self.verticalLayout.addLayout(self.search_line_layout)
        self.search_scrollArea = QtWidgets.QScrollArea(self.tab_search)
        self.search_scrollArea.setWidgetResizable(True)
        self.search_scrollArea.setObjectName("search_scrollArea")
        self.search_scrollArea.setStyleSheet("""
            QScrollBar:vertical {
                border: 1px solid #999999;
                background: #f0f0f0;
                width: 15px;
                margin: 20px 0 20px 0;
            }
            QScrollBar::handle:vertical {
                background: #99CCFF;
                min-height: 20px;
            }
            QScrollBar::add-line:vertical {
                background: none;
            }
            QScrollBar::sub-line:vertical {
                background: none;
            }
            
            QScrollBar:horizontal {
                border: 1px solid #99CCFF;
                background: #f0f0f0;
                margin: 0 20px 0 20px;
            }
            QScrollBar::handle:horizontal {
                background: #9900CC;
                min-height: 20px;
            }
            QScrollBar::add-line:horizontal {
                background: none;
            }
            QScrollBar::sub-line:horizontal {
                background: none;
            }
            """)
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 762, 518))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_movie_widgets_layout = QtWidgets.QVBoxLayout()
        self.search_movie_widgets_layout.setObjectName("search_movie_widgets_layout")
        self.horizontalLayout_4.addLayout(self.search_movie_widgets_layout)
        self.search_scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.search_scrollArea)
        self.btn_start_quiz = QtWidgets.QPushButton(self.tab_search)
        self.btn_start_quiz.setEnabled(False)
        self.btn_start_quiz.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.btn_start_quiz.setObjectName("btn_start_quiz")
        self.verticalLayout.addWidget(self.btn_start_quiz)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/search.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_search, icon1, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie"))
        self.text_viewed.setText(_translate("MainWindow", "Просмотренное"))
        self.label_in_process.setText(_translate("MainWindow", "В разработке...."))
        self.btn_search.setText(_translate("MainWindow", "Поиск"))
        self.btn_start_quiz.setText(_translate("MainWindow", "Начать опрос"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
