# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_count_of_members.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetCountOfMembers(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 700)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_choose_count_of_members = QtWidgets.QLabel(Form)
        self.label_choose_count_of_members.setStyleSheet("font: 20pt \"Arial\";")
        self.label_choose_count_of_members.setObjectName("label_choose_count_of_members")
        self.horizontalLayout.addWidget(self.label_choose_count_of_members)
        self.spinBox_count_of_members = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_count_of_members.sizePolicy().hasHeightForWidth())
        self.spinBox_count_of_members.setSizePolicy(sizePolicy)
        self.spinBox_count_of_members.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_count_of_members.setStyleSheet("QSpinBox {\n"
"    font: 20pt \"Arial\";\n"
"    padding-right: 15px; /* make room for the arrows */\n"
"    border-width: 3;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"\n"
"    width: 16px; /* 16 + 2*1px border-width = 15px padding + 3px parent border */\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* position at bottom right corner */\n"
"    width: 16px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    width: 7px;\n"
"    height: 7px;\n"
"}\n"
"")
        self.spinBox_count_of_members.setMinimum(1)
        self.spinBox_count_of_members.setMaximum(99)
        self.spinBox_count_of_members.setObjectName("spinBox_count_of_members")
        self.horizontalLayout.addWidget(self.spinBox_count_of_members)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_next_window = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next_window.sizePolicy().hasHeightForWidth())
        self.btn_next_window.setSizePolicy(sizePolicy)
        self.btn_next_window.setMinimumSize(QtCore.QSize(300, 0))
        self.btn_next_window.setStyleSheet("font: 20pt \"Arial\";")
        self.btn_next_window.setObjectName("btn_next_window")
        self.horizontalLayout_2.addWidget(self.btn_next_window)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_choose_count_of_members.setText(_translate("Form", "Выберите количество участников:"))
        self.btn_next_window.setText(_translate("Form", "ДАЛЕЕ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_WidgetCountOfMembers()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
